language: rust
rust:
  - 1.44.0  # pinned toolchain for clippy
  - 1.41.0  # minimum supported toolchain
  - stable
  - beta
  - nightly

arch:
  - amd64
  - s390x

matrix:
  allow_failures:
    - rust: nightly
    # VM apparently has broken network access
    - rust: 1.41.0
      arch: s390x

env:
  global:
    - CLIPPY_RUST_VERSION=1.44.0

before_script:
  - bash -c 'if [[ "$TRAVIS_RUST_VERSION" == "$CLIPPY_RUST_VERSION" ]]; then
      rustup component add clippy;
    fi'

script:
  - cargo test
  - cargo test --features rdcore
  - bash -c 'if [[ "$TRAVIS_RUST_VERSION" == "$CLIPPY_RUST_VERSION" ]]; then
      cargo clippy -- -D warnings;
      cargo clippy --features rdcore -- -D warnings;
    fi'
